const REVIEW_MARKER = '<!-- gitsense-ai-review -->';
const SUMMARY_MARKER = '<!-- gitsense-ai-summary -->';

export function formatReviewComment(state) {
  const summary = state.reviewSummary || {};
  const risk = buildRiskBadge(state.riskLevel || summary.riskLevel, state.riskScore);
  const confidence = buildConfidenceBadge(state.confidence ?? summary.confidence);
  const severity = normalizeLabel(state.severity || summary.severity || 'LOW');
  const affectedSystems = firstNonEmpty(summary.affectedSystems, state.affectedModules);
  const architecturalFindings = firstNonEmpty(
    summary.topFindings,
    state.aiReview?.findings,
    state.ruleFindings
  );
  const suggestions = firstNonEmpty(
    summary.suggestedChanges,
    state.aiReview?.suggestedChanges,
    summary.suggestedNextSteps
  );
  const criticalFiles = normalizeCriticalFiles(
    firstNonEmpty(summary.criticalFiles, state.criticalFiles, state.prioritizedFiles)
  );

  return [
    REVIEW_MARKER,
    '# GitSense AI Review',
    '',
    '## Risk Assessment',
    '',
    `- Risk Score: **${formatRiskScore(state.riskScore ?? summary.riskScore)} / 10**`,
    `- Risk: **${risk.label}**`,
    `- Confidence: **${confidence.percent}% (${confidence.label})**`,
    `- Severity: **${severity}**`,
    `- Architectural Impact: **${normalizeLabel(summary.architectureImpact || 'NOT_ANALYZED')}**`,
    '',
    formatSection('Affected Systems', affectedSystems, item => formatNamedItem(item)),
    '',
    formatSection('Architectural Findings', architecturalFindings, formatFinding),
    '',
    formatSection('Suggestions', suggestions, item => formatNamedItem(item)),
    '',
    formatSection('Critical Files', criticalFiles, file => file),
    '',
    '_Generated by GitSense AI._',
  ].join('\n');
}

export function formatSummaryComment(state, generatedSummary) {
  const summary = generatedSummary || {};
  const risk = buildRiskBadge(summary.riskLevel, summary.riskScore);
  const confidence = buildConfidenceBadge(summary.confidence);

  return [
    SUMMARY_MARKER,
    '# GitSense AI Summary',
    '',
    summary.executiveSummary,
    '',
    formatSection('Potentially Affected Systems', summary.affectedSystems, item =>
      formatNamedItem(item)
    ),
    '',
    '## Overall Risk',
    '',
    `- Risk: **${risk.label}**`,
    `- Risk Score: **${formatRiskScore(summary.riskScore)} / 10**`,
    `- Confidence: **${confidence.percent}% (${confidence.label})**`,
  ].join('\n');
}

export function buildCheckRunPayload(state, summary) {
  const riskScore = state.riskScore ?? summary?.riskScore ?? 0;
  const riskLevel = normalizeRiskLevel(state.riskLevel || summary?.riskLevel, riskScore);
  const severity = normalizeLabel(state.severity || summary?.severity || riskLevel);
  const checkStatus = mapRiskToCheckStatus(riskLevel, riskScore);
  const confidence = buildConfidenceBadge(state.confidence ?? summary?.confidence);
  const title = `GitSense AI Review: ${checkStatus.status}`;
  const reason = buildCheckReason({ riskLevel, severity, riskScore, state });

  return {
    name: 'GitSense AI Review',
    status: checkStatus.status,
    conclusion: checkStatus.conclusion,
    title,
    summary: reason,
    text: [
      `Risk: ${buildRiskBadge(riskLevel, riskScore).label}`,
      `Risk Score: ${formatRiskScore(riskScore)} / 10`,
      `Severity: ${severity}`,
      `Confidence: ${confidence.percent}% (${confidence.label})`,
      '',
      state.reviewSummary?.headline || summary?.executiveSummary || reason,
    ].join('\n'),
  };
}

export function getReviewCommentMarker() {
  return REVIEW_MARKER;
}

export function getSummaryCommentMarker() {
  return SUMMARY_MARKER;
}

export function buildRiskBadge(riskLevel, riskScore = 0) {
  const normalized = normalizeRiskLevel(riskLevel, riskScore);
  const labels = {
    LOW: 'GREEN LOW',
    MEDIUM: 'YELLOW MEDIUM',
    HIGH: 'ORANGE HIGH',
    CRITICAL: 'RED CRITICAL',
  };

  return {
    level: normalized,
    label: labels[normalized],
  };
}

export function buildConfidenceBadge(confidence = 0) {
  const percent = clampPercent(confidence);

  return {
    percent,
    label: percent >= 80 ? 'High Confidence' : percent >= 60 ? 'Medium Confidence' : 'Low Confidence',
  };
}

function mapRiskToCheckStatus(riskLevel, riskScore) {
  const normalized = normalizeRiskLevel(riskLevel, riskScore);

  if (normalized === 'CRITICAL') {
    return { status: 'CRITICAL', conclusion: 'failure' };
  }

  if (normalized === 'HIGH') {
    return { status: 'FAILED', conclusion: 'failure' };
  }

  if (normalized === 'MEDIUM') {
    return { status: 'WARNING', conclusion: 'neutral' };
  }

  return { status: 'PASSED', conclusion: 'success' };
}

function buildCheckReason({ riskLevel, severity, riskScore, state }) {
  if (riskLevel === 'CRITICAL') {
    return `Critical ${severity.toLowerCase()} risk detected with score ${formatRiskScore(riskScore)}.`;
  }

  if (riskLevel === 'HIGH') {
    return `High architectural risk detected with score ${formatRiskScore(riskScore)}.`;
  }

  if (riskLevel === 'MEDIUM') {
    return `Medium risk detected; review suggested findings before merge.`;
  }

  if ((state.reviewSummary?.topFindings || []).length > 0) {
    return 'Low risk review completed with non-blocking findings.';
  }

  return 'No critical architectural risks found.';
}

function formatSection(title, values, formatter) {
  const items = Array.isArray(values) ? values.filter(Boolean).slice(0, 10) : [];

  if (!items.length) {
    return `## ${title}\n\n- None detected`;
  }

  return [`## ${title}`, '', ...items.map(item => `- ${formatter(item)}`)].join('\n');
}

function formatFinding(finding) {
  const severity = finding.severity ? `[${normalizeLabel(finding.severity)}] ` : '';
  const title = finding.title || finding.ruleName || finding.ruleId || 'Finding';
  const path = finding.filePath || finding.filename || finding.path;
  const line = finding.line ? `:${finding.line}` : '';
  const location = path ? ` (${path}${line})` : '';
  const description = finding.description || finding.message;

  return `${severity}${title}${location}${description ? ` - ${description}` : ''}`;
}

function normalizeCriticalFiles(files = []) {
  return files
    .map(file => {
      if (typeof file === 'string') return file;
      return file.file || file.filename || file.path || file.filePath;
    })
    .filter(Boolean)
    .slice(0, 10);
}

function firstNonEmpty(...values) {
  return values.find(value => Array.isArray(value) && value.length > 0) || [];
}

function formatNamedItem(item) {
  if (typeof item === 'string') return item;
  return item.name || item.path || item.file || item.filename || JSON.stringify(item);
}

function formatRiskScore(score) {
  const value = Number(score);
  return Number.isFinite(value) ? value.toFixed(1).replace(/\.0$/, '') : '0';
}

function normalizeRiskLevel(riskLevel, riskScore = 0) {
  const label = normalizeLabel(riskLevel);

  if (['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'].includes(label)) {
    return label;
  }

  const score = Number(riskScore) || 0;
  if (score >= 8.5) return 'CRITICAL';
  if (score >= 6.5) return 'HIGH';
  if (score >= 3.5) return 'MEDIUM';
  return 'LOW';
}

function normalizeLabel(value) {
  return String(value || '').trim().toUpperCase().replace(/\s+/g, '_');
}

function clampPercent(value) {
  const percent = Number(value);

  if (!Number.isFinite(percent)) {
    return 0;
  }

  return Math.min(100, Math.max(0, Math.round(percent)));
}
